# Generated by Django 4.1.3 on 2022-11-25 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(choices=[('SMSA', 'SMSA'), ('ARAMEX', 'ARAMEX')], max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('estimated_shipping_date', models.DateField(null=True)),
                ('scheduled_at', models.DateField(null=True)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
                ('number_of_pieces', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tracking_id', models.CharField(max_length=35, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SCHEDULED', 'SCHEDULED'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=15)),
                ('shipper_name', models.CharField(max_length=250)),
                ('shipper_city', models.CharField(max_length=50)),
                ('shipper_country', models.CharField(max_length=50)),
                ('shipper_address', models.CharField(max_length=250)),
                ('shipper_phone', models.CharField(max_length=15)),
                ('receiver_name', models.CharField(max_length=250)),
                ('receiver_city', models.CharField(max_length=50)),
                ('receiver_country', models.CharField(max_length=50)),
                ('receiver_address', models.CharField(max_length=300)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
